# Generated by Django 4.2 on 2023-07-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dg_application', '0003_post_date_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='total_post_likes',
            field=models.IntegerField(default=0),
        ),
    ]
